# Generated by Django 6.0.5 on 2026-06-03 22:21

import django.db.models.functions.text
from django.db import migrations, models


def dedup_customer_names(apps, schema_editor):
    """
    Avant d'ajouter la contrainte d'unicité (shop, lower(name)), on renomme les
    doublons existants en suffixant `(2)`, `(3)`… au plus récent. On garde le
    plus ancien intact (id le plus petit en created_at).
    """
    Customer = apps.get_model('customers', 'Customer')
    seen: dict[tuple[str, str], int] = {}
    duplicates = (
        Customer.objects.order_by('shop_id', 'created_at', 'id')
        .values('id', 'shop_id', 'name')
    )
    for row in duplicates:
        key = (str(row['shop_id']), row['name'].strip().lower())
        seen[key] = seen.get(key, 0) + 1
        count = seen[key]
        if count == 1:
            continue  # le premier garde son nom
        new_name = f"{row['name']} ({count})"
        Customer.objects.filter(pk=row['id']).update(name=new_name)


def noop_reverse(apps, schema_editor):
    """Pas de rollback automatique des renommages — opération non destructive."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_first_name_to_customer'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedup_customer_names, noop_reverse),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('shop'), name='unique_customer_name_per_shop'),
        ),
    ]
