# Generated by Django 6.0.5 on 2026-05-17 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('stock_entry', 'Entrée stock'), ('stock_exit', 'Sortie stock'), ('stock_adjustment', 'Ajustement stock'), ('order_status_change', 'Changement statut commande'), ('order_payment_change', 'Changement paiement commande'), ('customer_delete', 'Suppression client'), ('product_delete', 'Suppression produit'), ('product_deactivate', 'Désactivation produit')], max_length=30)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('object_repr', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop_id', 'created_at'], name='audit_logs_shop_id_db6c42_idx')],
            },
        ),
    ]
