# Generated by Django 6.0.6 on 2026-06-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('stock_entry', 'Entrée stock'), ('stock_exit', 'Sortie stock'), ('stock_adjustment', 'Ajustement stock'), ('order_created', 'Création commande'), ('order_status_change', 'Changement statut commande'), ('order_payment_change', 'Changement paiement commande'), ('customer_delete', 'Suppression client'), ('product_delete', 'Suppression produit'), ('product_deactivate', 'Désactivation produit')], max_length=30),
        ),
    ]
