import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "max-lines-per-function": ["error", { max: 80, skipBlankLines: true, skipComments: true }],
    },
  },
  // Dette : à retirer de cette liste quand le fichier est découpé
  {
    files: [
      "**/customers/*/page.tsx",
      "**/customers/page.tsx",
      "**/invoices/*/page.tsx",
      "**/notes/page.tsx",
      "**/orders/*/edit/page.tsx",
      "**/orders/*/page.tsx",
      "**/products/*/page.tsx",
      "**/products/page.tsx",
      "**/reminders/page.tsx",
      "**/settings/subscription/page.tsx",
      "**/stock/add/page.tsx",
      "**/stock/import-invoice/page.tsx",
      "**/stock/out/page.tsx",
      "**/stock/page.tsx",
      "**/zakat/*/page.tsx",
      "**/zakat/new/page.tsx",
      "**/zakat/page.tsx",
      "**/login/page.tsx",
      "**/register/page.tsx",
      "**/reset-password/page.tsx",
      "**/onboarding/page.tsx",
      "components/customers/detail/CustomerActivityTimeline.tsx",
      "components/customers/list/FilterSortSheet.tsx",
      "components/layout/BottomNav.tsx",
      "components/layout/BurgerMenu.tsx",
      "components/layout/SearchOverlay.tsx",
      "components/layout/TopBar.tsx",
      "components/marketing/Nav.tsx",
      "components/marketing/screens/AppCommandes.tsx",
      "components/marketing/screens/AppHome.tsx",
      "components/messages/PreparedMessageDialog.tsx",
      "components/ocr/MatchingCandidatesSheet.tsx",
      "components/orders/CustomerPicker.tsx",
      "components/orders/detail/OrderHeroCard.tsx",
      "components/orders/detail/OrderNotesCard.tsx",
      "components/orders/detail/PaymentBottomSheet.tsx",
      "components/orders/picker/PickView.tsx",
      "components/products/list/OptionsSheet.tsx",
      "components/products/ProductForm.tsx",
      "components/products/variants/VariantEditor.tsx",
      "components/products/variants/VariantRow.tsx",
      "components/public-page-admin/ContactsCard.tsx",
      "components/public-page-admin/CoverUploader.tsx",
      "components/public-page-admin/IdentityCard.tsx",
      "components/public-page-admin/LogoUploader.tsx",
      "components/public-page-admin/MessageTemplateCard.tsx",
      "components/public-page-admin/SectionsCard.tsx",
      "components/settings/LogoUploader.tsx",
      "components/team/MemberFormSheet.tsx",
      "components/ui/AddressAutocomplete.tsx",
      "components/ui/ImageCropDialog.tsx",
      "components/ui/ThemeToggle.tsx",
      "components/zakat/SimulationSlider.tsx",
      "components/zakat/Step1Receivables.tsx",
      "components/zakat/Step2Stock.tsx",
      "components/zakat/Step4Debts.tsx",
      "components/zakat/Step5Summary.tsx",
      "lib/themes.ts",
      "lib/zakat-audit.ts",
    ],
    rules: {
      "max-lines-per-function": "off",
    },
  },
]);

export default eslintConfig;
