# Generated by Django 6.0.6 on 2026-06-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_last_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
