# Generated by Django 6.0.6 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_trial_consumed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_theme',
            field=models.CharField(
                blank=True,
                choices=[
                    ('default', 'Défaut'), ('warm', 'Chaud'), ('sky', 'Ciel'),
                    ('blush', 'Blush'), ('rosé', 'Rosé'), ('mint', 'Menthe'),
                    ('straw', 'Paille'), ('lavender', 'Lavande'), ('steel', 'Acier'),
                    ('sage', 'Sauge'), ('peach', 'Pêche'), ('lilac', 'Lilas'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_color',
            field=models.CharField(
                blank=True,
                choices=[
                    ('default', 'Défaut'), ('blue', 'Bleu'), ('purple', 'Violet'),
                    ('indigo', 'Indigo'), ('magenta', 'Fuchsia'), ('rose', 'Rose'),
                    ('red', 'Rouge'), ('orange', 'Orange'), ('amber', 'Ambre'),
                    ('forest', 'Forêt'), ('mint', 'Menthe'), ('cyan', 'Cyan'),
                    ('slate', 'Ardoise'), ('taupe', 'Taupe'), ('charcoal', 'Anthracite'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(
                blank=True,
                choices=[('system', 'Système'), ('light', 'Clair'), ('dark', 'Sombre')],
                max_length=10,
                null=True,
            ),
        ),
    ]
