# Generated by Django 6.0.6 on 2026-10-06 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_appearance_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_custom_hex',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Couleur hex attendue, ex. #ffffff.')]),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_color_custom_hex',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Couleur hex attendue, ex. #3b82f6.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_theme',
            field=models.CharField(blank=True, choices=[('default', 'Défaut'), ('warm', 'Chaud'), ('sky', 'Ciel'), ('blush', 'Blush'), ('rosé', 'Rosé'), ('mint', 'Menthe'), ('straw', 'Paille'), ('lavender', 'Lavande'), ('steel', 'Acier'), ('sage', 'Sauge'), ('peach', 'Pêche'), ('lilac', 'Lilas'), ('custom', 'Personnalisée')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('default', 'Défaut'), ('blue', 'Bleu'), ('purple', 'Violet'), ('indigo', 'Indigo'), ('magenta', 'Fuchsia'), ('rose', 'Rose'), ('red', 'Rouge'), ('orange', 'Orange'), ('amber', 'Ambre'), ('forest', 'Forêt'), ('mint', 'Menthe'), ('cyan', 'Cyan'), ('slate', 'Ardoise'), ('taupe', 'Taupe'), ('charcoal', 'Anthracite'), ('custom', 'Personnalisée')], max_length=20, null=True),
        ),
    ]
