# Generated by Django 6.0.6 on 2026-10-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_background_custom_hex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_theme',
            field=models.CharField(blank=True, choices=[('default', 'Défaut'), ('cream', 'Crème'), ('warm', 'Chaud'), ('sky', 'Ciel'), ('blush', 'Blush'), ('rosé', 'Rosé'), ('mint', 'Menthe'), ('straw', 'Paille'), ('lavender', 'Lavande'), ('steel', 'Acier'), ('sage', 'Sauge'), ('peach', 'Pêche'), ('lilac', 'Lilas'), ('custom', 'Personnalisée')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('default', 'Défaut'), ('blue', 'Bleu'), ('purple', 'Violet'), ('indigo', 'Indigo'), ('magenta', 'Fuchsia'), ('rose', 'Rose'), ('red', 'Rouge'), ('orange', 'Orange'), ('amber', 'Ambre'), ('forest', 'Forêt'), ('mint', 'Menthe'), ('sage', 'Sauge'), ('cyan', 'Cyan'), ('slate', 'Ardoise'), ('taupe', 'Taupe'), ('charcoal', 'Anthracite'), ('custom', 'Personnalisée')], max_length=20, null=True),
        ),
    ]
