# Generated by Django 6.0.5 on 2026-05-17 13:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_date', models.DateField()),
                ('stock_value_estimated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock_value_adjusted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('receivables_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('short_term_debts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('zakat_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('zakat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), max_digits=5)),
                ('zakat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('pdf_object_key', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_calculations', to='shops.shop')),
            ],
            options={
                'db_table': 'zakat_calculations',
                'ordering': ['-reference_date'],
            },
        ),
    ]
