# Generated by Django 6.0.5 on 2026-06-04 14:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('zakat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakatcalculation',
            options={'ordering': ['-reference_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='debts_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='excluded_items_acknowledged',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='has_receivables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='receivables_nominal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('finalized', 'Finalisé')], default='draft', max_length=16),
        ),
        migrations.AddIndex(
            model_name='zakatcalculation',
            index=models.Index(fields=['shop', 'status'], name='zakat_calcu_shop_id_242881_idx'),
        ),
    ]
