# Generated by Django 6.0.6 on 2026-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat', '0003_backfill_finalized_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatcalculation',
            name='receivables_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='stock_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
