# Generated by Django 6.0.6 on 2026-06-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat', '0004_zakatcalculation_receivables_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatcalculation',
            name='nisab_method',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='nisab_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='zakatcalculation',
            name='nisab_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
