# Generated by Django 6.0.6 on 2026-06-04 17:07

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_nisab_method_shop_nisab_unit_price'),
        ('zakat', '0005_zakatcalculation_nisab_method_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='zakatcalculation',
            constraint=models.UniqueConstraint(models.F('shop'), django.db.models.functions.datetime.ExtractYear('reference_date'), condition=models.Q(('status', 'finalized')), name='unique_finalized_zakat_per_shop_year'),
        ),
    ]
