# Generated by Django 6.0.6 on 2026-08-11 18:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0006_shop_catalog_kind_shop_dashboard_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('supplier_invoice', 'Facture fournisseur'), ('customer_address', 'Adresse client'), ('other', 'Autre')], max_length=30)),
                ('object_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='shops.shop')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcrResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec'), ('validated', 'Validé')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))])),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='shops.shop')),
                ('validated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_ocr_results', to=settings.AUTH_USER_MODEL)),
                ('uploaded_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='ocr.uploadeddocument')),
            ],
            options={
                'db_table': 'ocr_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['shop', '-created_at'], name='uploaded_do_shop_id_a5ce79_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['shop', '-created_at'], name='ocr_results_shop_id_885c92_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['shop', 'status'], name='ocr_results_shop_id_6e57a2_idx'),
        ),
    ]
