# Generated by Django 6.0.5 on 2026-05-17 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shops.shop')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='products_shop_id_ec9b58_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'name'], name='products_shop_id_21786f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'reference'], name='products_shop_id_e31cec_idx'),
        ),
    ]
