# Generated by Django 6.0.5 on 2026-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_unique_product_name_per_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('product', 'Produit'), ('service', 'Service')], default='product', max_length=10),
        ),
    ]
