# Generated by Django 6.0.5 on 2026-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Pièce'), ('g', 'Gramme'), ('kg', 'Kilogramme'), ('mL', 'Millilitre'), ('L', 'Litre'), ('m', 'Mètre'), ('h', 'Heure')], default='piece', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
