# Generated by Django 6.0.5 on 2026-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit_alter_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Pièce'), ('g', 'Gramme'), ('kg', 'Kilogramme'), ('mL', 'Millilitre'), ('L', 'Litre'), ('m', 'Mètre')], default='piece', max_length=8),
        ),
    ]
