# Generated by Django 6.0.5 on 2026-06-03 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_unit'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packaging_name', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('piece', 'Pièce'), ('g', 'Gramme'), ('kg', 'Kilogramme'), ('mL', 'Millilitre'), ('L', 'Litre'), ('m', 'Mètre')], default='piece', max_length=8)),
                ('base_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='shops.shop')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['shop', 'product'], name='product_var_shop_id_4f3d1e_idx'), models.Index(fields=['shop', 'sku'], name='product_var_shop_id_7e83ea_idx'), models.Index(fields=['shop', 'barcode'], name='product_var_shop_id_59b9e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'packaging_name'), name='unique_variant_packaging_per_product'), models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('shop', 'sku'), name='unique_variant_sku_per_shop')],
            },
        ),
    ]
