# Generated by Django 6.0.5 on 2026-06-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_backfill_default_variants'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_shop_id_e31cec_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
