# Generated by Django 6.0.5 on 2026-06-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_products_shop_id_e31cec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='base_quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantité contenue par format (ex. 250 pour "Bouteille 250 mL").', max_digits=14),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Nombre de formats en stock (ex. 50 bouteilles), pas le contenu cumulé.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('piece', 'Pièce'), ('g', 'Gramme'), ('kg', 'Kilogramme'), ('mL', 'Millilitre'), ('L', 'Litre'), ('m', 'Mètre')], default='piece', help_text='Unité de mesure du contenu (g, kg, mL…). Descriptif uniquement, sert au prix au litre/kilo.', max_length=8),
        ),
    ]
