# Generated by Django 6.0.6 on 2026-06-06 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_unique_customer_name_per_shop'),
        ('shops', '0004_remove_shop_invoice_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('tracking', 'Suivi de colis'), ('unpaid_followup', 'Relance impayé'), ('promo', 'Promotion'), ('free', 'Libre')], max_length=30)),
                ('context_type', models.CharField(choices=[('order', 'Commande'), ('customer', 'Client'), ('product', 'Produit'), ('none', 'Aucun')], default='none', max_length=30)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('prepared', 'Préparé'), ('sent_manually', 'Envoyé manuellement'), ('archived', 'Archivé')], default='prepared', max_length=20)),
                ('sent_manually_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_messages', to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_messages', to='shops.shop')),
            ],
            options={
                'db_table': 'prepared_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='prepared_me_shop_id_d3f70a_idx'), models.Index(fields=['shop', 'status'], name='prepared_me_shop_id_942684_idx'), models.Index(fields=['shop', 'customer'], name='prepared_me_shop_id_908e4d_idx')],
            },
        ),
    ]
