# Generated by Django 6.0.6 on 2026-06-06 14:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_convert_low_stock_threshold'),
        ('shops', '0005_shopmember_permissions_alter_shopmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Slug invalide : minuscules, chiffres et tirets uniquement (pas en début ni fin).', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo_object_key', models.CharField(blank=True, max_length=500)),
                ('cover_object_key', models.CharField(blank=True, max_length=500)),
                ('theme', models.CharField(choices=[('classic', 'Classique'), ('modern', 'Moderne'), ('minimal', 'Minimaliste')], default='classic', max_length=20)),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Couleur hex attendue, ex. #0ea5e9.')])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_page', to='shops.shop')),
            ],
            options={
                'db_table': 'public_pages',
            },
        ),
        migrations.CreateModel(
            name='PublicCatalogVisibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('show_price', models.BooleanField(default=True)),
                ('badge_promo', models.BooleanField(default=False)),
                ('badge_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_visibilities', to='products.product')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='public_pages.publicpage')),
            ],
            options={
                'db_table': 'public_catalog_visibilities',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['page', 'position'], name='public_cata_page_id_58a940_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'product'), name='unique_visibility_per_page_product')],
            },
        ),
        migrations.CreateModel(
            name='ContactButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('phone', 'Téléphone')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_buttons', to='public_pages.publicpage')),
            ],
            options={
                'db_table': 'public_page_contact_buttons',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('page', 'type'), name='unique_contact_type_per_page')],
            },
        ),
        migrations.CreateModel(
            name='PublicPageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('header', 'En-tête'), ('description', 'Description'), ('products', 'Produits'), ('services', 'Services'), ('contact', 'Contact')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='public_pages.publicpage')),
            ],
            options={
                'db_table': 'public_page_sections',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('page', 'type'), name='unique_section_type_per_page')],
            },
        ),
    ]
