# Generated by Django 6.0.6 on 2026-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='order_message_template',
            field=models.TextField(blank=True, default='Bonjour {shop_name}, je suis intéressé(e) par : {item_name}{price}.', max_length=500),
        ),
    ]
