# Generated by Django 6.0.5 on 2026-06-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stock_in_format_units'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='stock_movem_shop_id_250df9_idx',
            old_name='stock_movem_shop_id_variant_idx',
        ),
    ]
