# Generated by Django 6.0.6 on 2026-10-05 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_unique_customer_name_per_shop'),
        ('orders', '0006_order_updated_by'),
        ('shops', '0006_shop_catalog_kind_shop_dashboard_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_points_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='shops.shop')),
            ],
            options={
                'db_table': 'loyalty_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('points_per_unit', models.PositiveIntegerField(default=1)),
                ('redemption_threshold', models.PositiveIntegerField(default=100)),
                ('redemption_value', models.DecimalField(decimal_places=2, default='5.00', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='shops.shop')),
            ],
            options={
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Gain'), ('redeem', 'Remboursement'), ('adjust', 'Ajustement manuel'), ('expire', 'Expiration')], max_length=10)),
                ('points', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltycard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='shops.shop')),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loyaltycard',
            index=models.Index(fields=['shop', 'customer'], name='loyalty_car_shop_id_37f713_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycard',
            index=models.Index(fields=['shop', 'points_balance'], name='loyalty_car_shop_id_ce103e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltycard',
            unique_together={('shop', 'customer')},
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['shop', 'card'], name='loyalty_tra_shop_id_2cee42_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['shop', 'created_at'], name='loyalty_tra_shop_id_902392_idx'),
        ),
    ]
