# Generated by Django 6.0.6 on 2026-06-04 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_unique_customer_name_per_shop'),
        ('orders', '0005_orderitem_drop_product'),
        ('shops', '0003_shop_default_payment_terms_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('issued', 'Émise'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='issued', max_length=12)),
                ('issued_at', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('seller_name', models.CharField(max_length=120)),
                ('seller_address', models.TextField(blank=True)),
                ('seller_tax_id', models.CharField(blank=True, max_length=64)),
                ('seller_legal_mentions', models.TextField(blank=True)),
                ('seller_country', models.CharField(blank=True, max_length=2)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_city', models.CharField(blank=True, max_length=100)),
                ('buyer_postal_code', models.CharField(blank=True, max_length=20)),
                ('buyer_country', models.CharField(blank=True, max_length=2)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('pdf_object_key', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='orders.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shops.shop')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_subtotal_ht', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='shops.shop')),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='shops.shop')),
            ],
            options={
                'db_table': 'invoice_sequences',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shop', '-issued_at'], name='invoices_shop_id_40c0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shop', 'status'], name='invoices_shop_id_681e11_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('shop', 'number'), name='unique_invoice_number_per_shop'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice'], name='invoice_lin_invoice_019757_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(fields=('shop', 'year'), name='unique_invoice_sequence_per_shop_year'),
        ),
    ]
