# Generated by Django 6.0.6 on 2026-06-04 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('shops', '0004_remove_shop_invoice_prefix'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicesequence',
            name='unique_invoice_sequence_per_shop_year',
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequence', to='shops.shop'),
        ),
        migrations.RemoveField(
            model_name='invoicesequence',
            name='year',
        ),
    ]
