# Generated by Django 6.0.6 on 2026-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
