# Generated by Django 6.0.5 on 2026-06-01 20:56

from django.db import migrations


def migrate_order_notes_to_note_model(apps, schema_editor):
    """Copie chaque Order.notes non-vide en une Note attachée à la commande."""
    Order = apps.get_model('orders', 'Order')
    Note = apps.get_model('notes', 'Note')
    notes_to_create = []
    for order in Order.objects.exclude(notes='').only('id', 'shop_id', 'notes', 'created_by_id', 'created_at'):
        notes_to_create.append(Note(
            shop_id=order.shop_id,
            order_id=order.id,
            author_id=order.created_by_id,
            content=order.notes,
            created_at=order.created_at,
            updated_at=order.created_at,
        ))
    if notes_to_create:
        Note.objects.bulk_create(notes_to_create)


def reverse_noop(apps, schema_editor):
    """Pas de rollback : on perdrait les notes créées après la migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_order_notes_to_note_model, reverse_noop),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
