# Generated by Django 6.0.6 on 2026-06-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='nisab_method',
            field=models.CharField(choices=[('gold', 'Or (85 g)'), ('silver', 'Argent (595 g)')], default='silver', max_length=8),
        ),
        migrations.AddField(
            model_name='shop',
            name='nisab_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
