# Generated by Django 6.0.6 on 2026-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_nisab_method_shop_nisab_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='default_payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='legal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='legal_mentions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
