# Generated by Django 6.0.6 on 2026-06-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_default_payment_terms_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='invoice_prefix',
        ),
    ]
