# Generated by Django 6.0.6 on 2026-06-06 12:06

from django.db import migrations, models


def rename_manager_to_admin(apps, schema_editor):
    ShopMember = apps.get_model('shops', 'ShopMember')
    ShopMember.objects.filter(role='manager').update(role='admin')


def rename_admin_to_manager(apps, schema_editor):
    ShopMember = apps.get_model('shops', 'ShopMember')
    ShopMember.objects.filter(role='admin').update(role='manager')


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_shop_invoice_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmember',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(rename_manager_to_admin, rename_admin_to_manager),
        migrations.AlterField(
            model_name='shopmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], default='owner', max_length=20),
        ),
    ]
