# Generated by Django 6.0.6 on 2026-06-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shopmember_permissions_alter_shopmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='catalog_kind',
            field=models.CharField(choices=[('products', 'Produits'), ('services', 'Services'), ('both', 'Les deux')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='dashboard_mode',
            field=models.CharField(choices=[('minimal', 'Minimaliste'), ('complete', 'Complet')], default='complete', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
