# Generated by Django 6.0.6 on 2026-10-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_catalog_kind_shop_dashboard_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='dashboard_mode',
        ),
        migrations.AddField(
            model_name='shop',
            name='fulfillment_mode',
            field=models.CharField(blank=True, choices=[('on_site', 'Sur place'), ('delivery', 'En livraison'), ('both', 'Les deux')], max_length=10, null=True),
        ),
    ]
